In [1]:
categories = ["entertainment", "sports", "technology", "politics"]
type(categories)

list

In [3]:
cat_list = []
data_list = []
for cat in categories:
    print(cat)
    with open('{}.txt'.format(cat)) as f:
    #lines = [line.rstrip('\n') for line in open('{}.txt'.format(cat))]
        lines=f.readlines()
        lines = [x.strip() for x in lines]
        data_list.extend(lines)
        le = len(lines)
        for r in range(le):
            cat_list.append(cat)

entertainment
sports
technology
politics


In [4]:
print(len(data_list))
#print(data_list)
print(len(cat_list))
#print(cat_list)

3468
3468


In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
target = le.fit_transform(cat_list)
print(len(target))
print(target)

3468
[0 0 0 ... 1 1 1]


In [6]:
import pandas as pd
d = {'Headlines':data_list, 'Category':cat_list, 'Target': target}
#print(d)
df = pd.DataFrame(d)
print(df.iloc[1000])

Headlines    Cricket News: Former Indian pacer Roger Binny ...
Category                                                sports
Target                                                       2
Name: 1000, dtype: object


In [7]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
x_train_tf = count_vect.fit_transform(data_list)
print(type(data_list))
print(x_train_tf.shape)
print(x_train_tf.toarray())

<class 'list'>
(3468, 10898)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_tf)
x_train_tfidf.shape

(3468, 10898)

In [9]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train_tfidf, target)

In [10]:
print(categories)
print(target)

['entertainment', 'sports', 'technology', 'politics']
[0 0 0 ... 1 1 1]


In [11]:
test_data = []
with open('headlines.txt', 'r+', encoding='utf-8') as f:
    lines = f.readlines()
    lines = [x.strip() for x in lines]
    test_data.extend(lines)
print(len(test_data))

50


In [12]:
#test_data = ["The value of losses from crime in the digital currency sector in 2018 hit $1.7 billion.", "15 jawans killed after Naxals trigger IED blast in Maharashtra's Gadchiroli.",  "iPhone XS specs vs. XS Max, XR, X: What's the same and different", "2 People Injured In Indiana School Shooting", "Twitter Bots May Have Delivered Donald Trump's Victory, Research Paper Says", "60 Seconds of Social Media", "My Son Only Read One Book in Middle School"]
#test_data = ["Most developers should be familiar with Google's cross-platform, portable UI framework Flutter, which can make developing apps for both Android and iOS a whole lot easier. In fact, it just recently hit 1.0 late last year. Today, at the company's I/O developer"]

x_test_tf = count_vect.transform(test_data)
x_test_tfidf = tfidf_transformer.transform(x_test_tf)
predicted = clf.predict(x_test_tfidf)

In [23]:
print(predicted)

[3 1 2 1 1 1 3 1 1 1 1 1 3 1 3 1 1 0 1 3 3 1 3 1 3 2 2 2 2 2 1 1 1 1 1 1 2
 1 1 1 1 2 2 1 1 1 1 1 1 1]


In [24]:
test_cat_list = []
for x in predicted:
    if x == 0:
        test_cat_list.append('entertainment')
    #elif x == 1:
    #    test_cat_list.append('general')
    elif x == 1:
        test_cat_list.append('politics')
    elif x == 2:
        test_cat_list.append('sports')
    elif x == 3:
        test_cat_list.append('technology')
print(len(test_cat_list))
print(test_cat_list)

50
['technology', 'politics', 'sports', 'politics', 'politics', 'politics', 'technology', 'politics', 'politics', 'politics', 'politics', 'politics', 'technology', 'politics', 'technology', 'politics', 'politics', 'entertainment', 'politics', 'technology', 'technology', 'politics', 'technology', 'politics', 'technology', 'sports', 'sports', 'sports', 'sports', 'sports', 'politics', 'politics', 'politics', 'politics', 'politics', 'politics', 'sports', 'politics', 'politics', 'politics', 'politics', 'sports', 'sports', 'politics', 'politics', 'politics', 'politics', 'politics', 'politics', 'politics']


In [14]:
#import pandas as pd
#d = {'Headlines':test_data, 'Category':test_cat_list}
#print(d)
#dfd = pd.DataFrame(d)
#print(dfd)

In [15]:
#Direct Method --------------------
import sklearn.datasets as skd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [16]:
text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])


In [17]:
text_clf.fit(data_list, target)
predicted = text_clf.predict(test_data)
pred_prob = text_clf.predict_proba(test_data)

In [18]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np

In [19]:
#predicted
pred_prob 

array([[0.23774716, 0.22516424, 0.17443009, 0.36265851],
       [0.02426427, 0.91565469, 0.03318355, 0.02689749],
       [0.19631415, 0.2205969 , 0.33154805, 0.25154089],
       [0.05634279, 0.50761049, 0.13244016, 0.30360656],
       [0.12255116, 0.52519723, 0.09441743, 0.25783418],
       [0.07750519, 0.47067979, 0.30157305, 0.15024197],
       [0.06169474, 0.3756234 , 0.14808358, 0.41459829],
       [0.24281698, 0.41685726, 0.11913673, 0.22118902],
       [0.10488739, 0.62168669, 0.12967127, 0.14375465],
       [0.10682111, 0.64054658, 0.1639029 , 0.08872941],
       [0.18197706, 0.32978172, 0.2135463 , 0.27469492],
       [0.1148175 , 0.62447102, 0.17897649, 0.08173498],
       [0.04019372, 0.32607759, 0.07403721, 0.55969148],
       [0.23054502, 0.37742533, 0.30626851, 0.08576114],
       [0.0480606 , 0.23645742, 0.09727185, 0.61821013],
       [0.25936654, 0.3066459 , 0.30280131, 0.13118625],
       [0.14606022, 0.45039118, 0.14616422, 0.25738438],
       [0.40817437, 0.2175377 ,

In [25]:
type(pred_prob)
#print(len (pred_prob))
#print (pred_prob[0])
#print(np.amax(pred_prob[0]))
prob_list =[]
for i in range(len(pred_prob)):
    prob_list.append(np.amax(pred_prob[i]))
print (len(prob_list))
print (len(test_cat_list))
print (len(test_data))

50
50
50


In [26]:
d = {'Headlines':test_data, 'Category':test_cat_list, 'Probability':prob_list}
#print(d)
dfd = pd.DataFrame(d)
print(type(dfd))

<class 'pandas.core.frame.DataFrame'>


In [27]:
#fp = open('analysis.txt', 'w')
#fp.write(dfd)
#fp.close()
#np.savetxt(r'./analysis.txt', dfd.values, fmt='%s')
ds = dfd.applymap(str)
print(type(ds))
ds.to_csv('analysis.csv')
#np.savetxt(r'./analysis.txt', ds.values, fmt='%s',encoding="utf-8",header="Headlines\tCategories\tProbability")

<class 'pandas.core.frame.DataFrame'>
